# Generated by Django 2.2.7 on 2019-12-04 23:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ip', models.CharField(blank=True, default='', max_length=250)),
                ('country_code', models.CharField(blank=True, default='', max_length=250)),
                ('country_name', models.CharField(blank=True, default='', max_length=250)),
                ('country_flag', models.CharField(blank=True, default='', max_length=250)),
                ('calling_code', models.CharField(blank=True, default='', max_length=250)),
                ('currency', models.CharField(blank=True, default='', max_length=250)),
                ('mount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPagoEfectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('object', models.CharField(blank=True, default='', max_length=250)),
                ('create_data_time', models.IntegerField()),
                ('expiration_date_time', models.IntegerField()),
                ('orde_id', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('payment_code', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('currency_code', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('total_fee', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('net_amount', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('fee_details', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('updated_at', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('paid_at', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('available_on', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('firstname', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('data_payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status_object', models.CharField(blank=True, default='', max_length=300)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('charge_id', models.CharField(blank=True, default='', max_length=300)),
                ('type', models.CharField(blank=True, default='', max_length=300)),
                ('code', models.CharField(blank=True, default='', max_length=300)),
                ('reference_code', models.CharField(blank=True, default='', max_length=300)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=300)),
                ('merchant_message', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('data_payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('lastname', models.CharField(blank=True, default='', max_length=400)),
                ('phone', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
