# Generated by Django 2.2.7 on 2019-11-10 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontact',
            name='create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
