# Generated by Django 2.2.7 on 2019-11-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_modelcontact_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontact',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
