# Generated by Django 2.2.7 on 2019-11-14 17:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_modelcontact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status_object', models.CharField(blank=True, default='', max_length=300)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('charge_id', models.CharField(blank=True, default='', max_length=300)),
                ('type', models.CharField(blank=True, default='', max_length=300)),
                ('code', models.CharField(blank=True, default='', max_length=300)),
                ('reference_code', models.CharField(blank=True, default='', max_length=300)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=300)),
                ('merchant_message', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('data_payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('lastname', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
