# Generated by Django 2.2.7 on 2019-11-25 16:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_modelpagoefectivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpagoefectivo',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='modelpagoefectivo',
            name='data_payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
