# Generated by Django 2.2.7 on 2019-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_auto_20191125_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='available_on',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='currency_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='fee_details',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='net_amount',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='orde_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='paid_at',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='payment_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='state',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='total_fee',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelpagoefectivo',
            name='updated_at',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
