# Generated by Django 2.2.7 on 2019-12-04 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('url_alumno', models.CharField(default='', max_length=500, unique=True)),
                ('file_certificate', models.CharField(blank=True, default='', max_length=250)),
                ('taller_name', models.CharField(blank=True, default='', max_length=250)),
                ('nombre', models.CharField(blank=True, default='', max_length=250)),
                ('apellido', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
