# Generated by Django 2.2.7 on 2019-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelalumno',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='modelalumno',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='modelalumno',
            name='url_alumno',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
