# Generated by Django 2.2.7 on 2019-11-07 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('body', models.TextField()),
                ('url_image', models.CharField(default='', max_length=255)),
                ('resume', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
