# Generated by Django 2.2.7 on 2019-11-20 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ip', models.CharField(blank=True, default='', max_length=250)),
                ('country_code', models.CharField(blank=True, default='', max_length=250)),
                ('currency', models.CharField(blank=True, default='', max_length=250)),
                ('mount', models.FloatField(default=0.0)),
            ],
        ),
    ]
